version: "3.9"

services:

  nginx:
    depends_on:
      - mariadb
      - wordpress
    build: ./requirements/nginx
    image : nginx
    ports :
      - "443:443"
    networks:
      - mynet
    volumes:
      - /home/yqodsi/data/wp-data:/var/www/wordpress/
    restart: always

  mariadb :
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - /home/yqodsi/data/db-data:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - mynet
    restart: always
  
  wordpress :
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - /home/yqodsi/data/wp-data:/var/www/wordpress/
    ports:
      - "9000"
    networks:
      - mynet
    restart: always

networks:
  mynet:
    driver : bridge
